Remove phantomJS
stoarca/phantesta pull request #32
Opened 2021-06-11 15:19 UTC by gielow

2021-06-11 17:42 UTC, stoarca requested changes

2021-06-11 18:16 UTC, gielow commented on tests/spec/phantesta-spec.js
> +    fit('should test basic functionality', syncify(async function() {
Removed.

2021-06-11 18:16 UTC, gielow commented on README.md
> +   - `maxPhantestaServers` is the maximum number of phantesta server that will be run at any
Forgot to rebase on the latest.

2021-06-11 18:17 UTC, gielow commented on README.md
> +    phantesta.destructiveClearAllSnapshots();
Fixed.
Ps.: It was wrong on master.

2021-08-31 15:54 UTC, stoarca approved these changes

2021-08-31 15:54 UTC, stoarca commented on README.md
> +    phantesta.destructiveClearAllSnapshots();
Doesn't look like this was fixed.

2021-08-31 15:54 UTC, merged